accounts/urls.py
from django.urls import path, include
from .views import UserRegister

app_name = 'accounts'

urlpatterns = [
    path('register/', UserRegister.as_view()),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

accounts/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models


class Person(models.Model):
    name = models.CharField(max_length=50)
    age = models.PositiveBigIntegerField()
    email = models.EmailField()
    
    
    def __str__(self):
        return self.name
    

accounts/views.py
from django.shortcuts import render
from rest_framework.decorators import APIView
from .serializers import UserRegisterSerializer
from django.contrib.auth.models import User
from rest_framework.response import Response

class UserRegister(APIView):
    
    def post(self, request):
        ser_data = UserRegisterSerializer(data=request.POST)
        if ser_data.is_valid():
            User.objects.create_user(
                username=ser_data.validated_data['username'],
                email=ser_data.validated_data['email'],
                password=ser_data.validated_data['password']
            )
            return Response(ser_data.data)
        
        return Response(ser_data.errors)
            

home/views.py
from django.shortcuts import render
from django.views import View
from rest_framework.response import Response
from rest_framework.decorators import api_view, APIView
from .models import Person
from .serializers import PersonSerializer


class HomeView(APIView):
    def get(self, request):
        person = Person.objects.all()
        ser_data = PersonSerializer(instance=person, many=True)
        
        return Response(ser_data.data)

# @api_view(['GET', 'POST'])
# def home(request):
#     return Response({'name': 'ali',})


# class HomeView(View):
#     def get(self, request):
#         return render(request, 'home/home.html')

home/templates/home/home.html
{% extends 'base.html' %}

{% block content %}
<div class="container">

    <h3> home page </h3>

</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title></title>
</head>
<body>
    {% include 'inc/navbar.html' %}
    {% block content %} {% endblock %}
    
</body>
</html>

templates/inc/navbar.html
<nav class="navbar bg-body-tertiary" data-bs-theme="dark">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home:home' %}">Home</a>
    </div>
  </nav>